/* 지역 */
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '강북구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '도봉구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '노원구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '중랑구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '동대문구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '성북구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '종로구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '은평구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '서대문구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '마포구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '용산구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '중구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '성동구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '광진구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '강동구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '송파구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '강남구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '서초구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '동작구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '영등포구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '강서구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '양천구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '구로구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '금천구');
INSERT INTO REGION(SIDO, SIGG) VALUES ('서울특별시', '관악구');

--
-- INSERT INTO PERSONALITY(NAME) VALUES ('집돌이');
-- INSERT INTO PERSONALITY(NAME) VALUES ('애니메이션');
-- INSERT INTO PERSONALITY(NAME) VALUES ('영화감상');
-- INSERT INTO PERSONALITY(NAME) VALUES ('흡연');

